import type { Knex } from 'knex'

export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable('vpn_nodes', (table) => {
    table.string('id', 36).primary().notNullable()
    table.string('hostname', 255).notNullable()
    table.string('ip_address', 45).notNullable()
    table.integer('port').notNullable().defaultTo(1194)
    table.string('region', 100).nullable()
    table.string('token', 255).notNullable().unique()
    table.enu('status', ['online', 'offline']).notNullable().defaultTo('offline')
    table.string('vpn_type', 20).notNullable().defaultTo('openvpn')
    table.string('firewall_engine', 255).notNullable().defaultTo('iptables')
    table.string('version', 50).nullable()
    table.text('ca_cert').nullable()
    table.text('ta_key').nullable()
    table.text('private_key').nullable()
    table.text('public_key').nullable()
    table.integer('endpoint_port').nullable()
    table.timestamp('last_seen').nullable()
    table.string('protocol', 10).nullable().defaultTo('udp')
    table.string('tunnel_mode', 10).nullable().defaultTo('full')
    table.string('vpn_network', 18).nullable().defaultTo('10.8.0.0')
    table.string('vpn_netmask', 15).nullable().defaultTo('255.255.255.0')
    table.string('dns_servers', 500).nullable().defaultTo('8.8.8.8,1.1.1.1')
    table.text('push_routes').nullable()
    table.string('cipher', 50).nullable().defaultTo('AES-128-GCM')
    table.string('auth_digest', 20).nullable().defaultTo('SHA256')
    table.string('compression', 20).nullable().defaultTo('lz4-v2')
    table.integer('keepalive_ping').nullable().defaultTo(10)
    table.integer('keepalive_timeout').nullable().defaultTo(60)
    table.integer('max_clients').nullable().defaultTo(100)
    table.text('custom_push_directives').nullable()
    table.text('firewall_rules_dump').nullable()
    table.boolean('managed_dns_enabled').notNullable().defaultTo(false)
    table.boolean('managed_dns_capable').notNullable().defaultTo(false)
    table.integer('dns_config_revision').notNullable().defaultTo(0)
    table.string('dns_sync_status', 20).notNullable().defaultTo('disabled')
    table.text('dns_last_sync_error').nullable()
    table.timestamp('dns_last_synced_at').nullable()
    table.string('dns_config_hash', 71).nullable()
    table.text('wireguard_allowed_ips').nullable()
    table.timestamps(true, true)
  })
}

export async function down(knex: Knex): Promise<void> { await knex.schema.dropTableIfExists('vpn_nodes') }
