/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAlertsRouteImport } from './routes/_layout/alerts'
import { Route as LayoutAuditRouteImport } from './routes/_layout/audit'
import { Route as LayoutDnsRouteImport } from './routes/_layout/dns'
import { Route as LayoutGroupsRouteImport } from './routes/_layout/groups'
import { Route as LayoutNetworksRouteImport } from './routes/_layout/networks'
import { Route as LayoutNodesRouteImport } from './routes/_layout/nodes'
import { Route as LayoutPoliciesRouteImport } from './routes/_layout/policies'
import { Route as LayoutProfileRouteImport } from './routes/_layout/profile'
import { Route as LayoutSessionsRouteImport } from './routes/_layout/sessions'
import { Route as LayoutTasksRouteImport } from './routes/_layout/tasks'
import { Route as LayoutUsersRouteImport } from './routes/_layout/users'
import { Route as LayoutGroupsIndexRouteImport } from './routes/_layout/groups/index'
import { Route as LayoutGroupsGroupIdRouteImport } from './routes/_layout/groups/$groupId'
import { Route as LayoutUsersIndexRouteImport } from './routes/_layout/users/index'
import { Route as LayoutUsersUserIdCertificatesRouteImport } from './routes/_layout/users/$userId.certificates'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAlertsRoute = LayoutAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuditRoute = LayoutAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDnsRoute = LayoutDnsRouteImport.update({
  id: '/dns',
  path: '/dns',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGroupsRoute = LayoutGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNetworksRoute = LayoutNetworksRouteImport.update({
  id: '/networks',
  path: '/networks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNodesRoute = LayoutNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPoliciesRoute = LayoutPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileRoute = LayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSessionsRoute = LayoutSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTasksRoute = LayoutTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsersRoute = LayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGroupsIndexRoute = LayoutGroupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutGroupsRoute,
} as any)
const LayoutGroupsGroupIdRoute = LayoutGroupsGroupIdRouteImport.update({
  id: '/$groupId',
  path: '/$groupId',
  getParentRoute: () => LayoutGroupsRoute,
} as any)
const LayoutUsersIndexRoute = LayoutUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutUsersRoute,
} as any)
const LayoutUsersUserIdCertificatesRoute =
  LayoutUsersUserIdCertificatesRouteImport.update({
    id: '/$userId/certificates',
    path: '/$userId/certificates',
    getParentRoute: () => LayoutUsersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof LayoutAlertsRoute
  '/audit': typeof LayoutAuditRoute
  '/dns': typeof LayoutDnsRoute
  '/groups': typeof LayoutGroupsRouteWithChildren
  '/networks': typeof LayoutNetworksRoute
  '/nodes': typeof LayoutNodesRoute
  '/policies': typeof LayoutPoliciesRoute
  '/profile': typeof LayoutProfileRoute
  '/sessions': typeof LayoutSessionsRoute
  '/tasks': typeof LayoutTasksRoute
  '/users': typeof LayoutUsersRouteWithChildren
  '/groups/$groupId': typeof LayoutGroupsGroupIdRoute
  '/groups/': typeof LayoutGroupsIndexRoute
  '/users/': typeof LayoutUsersIndexRoute
  '/users/$userId/certificates': typeof LayoutUsersUserIdCertificatesRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/alerts': typeof LayoutAlertsRoute
  '/audit': typeof LayoutAuditRoute
  '/dns': typeof LayoutDnsRoute
  '/networks': typeof LayoutNetworksRoute
  '/nodes': typeof LayoutNodesRoute
  '/policies': typeof LayoutPoliciesRoute
  '/profile': typeof LayoutProfileRoute
  '/sessions': typeof LayoutSessionsRoute
  '/tasks': typeof LayoutTasksRoute
  '/': typeof LayoutIndexRoute
  '/groups/$groupId': typeof LayoutGroupsGroupIdRoute
  '/groups': typeof LayoutGroupsIndexRoute
  '/users': typeof LayoutUsersIndexRoute
  '/users/$userId/certificates': typeof LayoutUsersUserIdCertificatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/alerts': typeof LayoutAlertsRoute
  '/_layout/audit': typeof LayoutAuditRoute
  '/_layout/dns': typeof LayoutDnsRoute
  '/_layout/groups': typeof LayoutGroupsRouteWithChildren
  '/_layout/networks': typeof LayoutNetworksRoute
  '/_layout/nodes': typeof LayoutNodesRoute
  '/_layout/policies': typeof LayoutPoliciesRoute
  '/_layout/profile': typeof LayoutProfileRoute
  '/_layout/sessions': typeof LayoutSessionsRoute
  '/_layout/tasks': typeof LayoutTasksRoute
  '/_layout/users': typeof LayoutUsersRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/groups/$groupId': typeof LayoutGroupsGroupIdRoute
  '/_layout/groups/': typeof LayoutGroupsIndexRoute
  '/_layout/users/': typeof LayoutUsersIndexRoute
  '/_layout/users/$userId/certificates': typeof LayoutUsersUserIdCertificatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alerts'
    | '/audit'
    | '/dns'
    | '/groups'
    | '/networks'
    | '/nodes'
    | '/policies'
    | '/profile'
    | '/sessions'
    | '/tasks'
    | '/users'
    | '/groups/$groupId'
    | '/groups/'
    | '/users/'
    | '/users/$userId/certificates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/alerts'
    | '/audit'
    | '/dns'
    | '/networks'
    | '/nodes'
    | '/policies'
    | '/profile'
    | '/sessions'
    | '/tasks'
    | '/'
    | '/groups/$groupId'
    | '/groups'
    | '/users'
    | '/users/$userId/certificates'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/alerts'
    | '/_layout/audit'
    | '/_layout/dns'
    | '/_layout/groups'
    | '/_layout/networks'
    | '/_layout/nodes'
    | '/_layout/policies'
    | '/_layout/profile'
    | '/_layout/sessions'
    | '/_layout/tasks'
    | '/_layout/users'
    | '/_layout/'
    | '/_layout/groups/$groupId'
    | '/_layout/groups/'
    | '/_layout/users/'
    | '/_layout/users/$userId/certificates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/alerts': {
      id: '/_layout/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof LayoutAlertsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/audit': {
      id: '/_layout/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof LayoutAuditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dns': {
      id: '/_layout/dns'
      path: '/dns'
      fullPath: '/dns'
      preLoaderRoute: typeof LayoutDnsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/groups': {
      id: '/_layout/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof LayoutGroupsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/networks': {
      id: '/_layout/networks'
      path: '/networks'
      fullPath: '/networks'
      preLoaderRoute: typeof LayoutNetworksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/nodes': {
      id: '/_layout/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof LayoutNodesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/policies': {
      id: '/_layout/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof LayoutPoliciesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile': {
      id: '/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sessions': {
      id: '/_layout/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof LayoutSessionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tasks': {
      id: '/_layout/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof LayoutTasksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/users': {
      id: '/_layout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof LayoutUsersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/groups/': {
      id: '/_layout/groups/'
      path: '/'
      fullPath: '/groups/'
      preLoaderRoute: typeof LayoutGroupsIndexRouteImport
      parentRoute: typeof LayoutGroupsRoute
    }
    '/_layout/groups/$groupId': {
      id: '/_layout/groups/$groupId'
      path: '/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof LayoutGroupsGroupIdRouteImport
      parentRoute: typeof LayoutGroupsRoute
    }
    '/_layout/users/': {
      id: '/_layout/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof LayoutUsersIndexRouteImport
      parentRoute: typeof LayoutUsersRoute
    }
    '/_layout/users/$userId/certificates': {
      id: '/_layout/users/$userId/certificates'
      path: '/$userId/certificates'
      fullPath: '/users/$userId/certificates'
      preLoaderRoute: typeof LayoutUsersUserIdCertificatesRouteImport
      parentRoute: typeof LayoutUsersRoute
    }
  }
}

interface LayoutGroupsRouteChildren {
  LayoutGroupsGroupIdRoute: typeof LayoutGroupsGroupIdRoute
  LayoutGroupsIndexRoute: typeof LayoutGroupsIndexRoute
}

const LayoutGroupsRouteChildren: LayoutGroupsRouteChildren = {
  LayoutGroupsGroupIdRoute: LayoutGroupsGroupIdRoute,
  LayoutGroupsIndexRoute: LayoutGroupsIndexRoute,
}

const LayoutGroupsRouteWithChildren = LayoutGroupsRoute._addFileChildren(
  LayoutGroupsRouteChildren,
)

interface LayoutUsersRouteChildren {
  LayoutUsersIndexRoute: typeof LayoutUsersIndexRoute
  LayoutUsersUserIdCertificatesRoute: typeof LayoutUsersUserIdCertificatesRoute
}

const LayoutUsersRouteChildren: LayoutUsersRouteChildren = {
  LayoutUsersIndexRoute: LayoutUsersIndexRoute,
  LayoutUsersUserIdCertificatesRoute: LayoutUsersUserIdCertificatesRoute,
}

const LayoutUsersRouteWithChildren = LayoutUsersRoute._addFileChildren(
  LayoutUsersRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAlertsRoute: typeof LayoutAlertsRoute
  LayoutAuditRoute: typeof LayoutAuditRoute
  LayoutDnsRoute: typeof LayoutDnsRoute
  LayoutGroupsRoute: typeof LayoutGroupsRouteWithChildren
  LayoutNetworksRoute: typeof LayoutNetworksRoute
  LayoutNodesRoute: typeof LayoutNodesRoute
  LayoutPoliciesRoute: typeof LayoutPoliciesRoute
  LayoutProfileRoute: typeof LayoutProfileRoute
  LayoutSessionsRoute: typeof LayoutSessionsRoute
  LayoutTasksRoute: typeof LayoutTasksRoute
  LayoutUsersRoute: typeof LayoutUsersRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAlertsRoute: LayoutAlertsRoute,
  LayoutAuditRoute: LayoutAuditRoute,
  LayoutDnsRoute: LayoutDnsRoute,
  LayoutGroupsRoute: LayoutGroupsRouteWithChildren,
  LayoutNetworksRoute: LayoutNetworksRoute,
  LayoutNodesRoute: LayoutNodesRoute,
  LayoutPoliciesRoute: LayoutPoliciesRoute,
  LayoutProfileRoute: LayoutProfileRoute,
  LayoutSessionsRoute: LayoutSessionsRoute,
  LayoutTasksRoute: LayoutTasksRoute,
  LayoutUsersRoute: LayoutUsersRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
