/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutUsersRouteImport } from './routes/_layout/users'
import { Route as LayoutTasksRouteImport } from './routes/_layout/tasks'
import { Route as LayoutSessionsRouteImport } from './routes/_layout/sessions'
import { Route as LayoutProfileRouteImport } from './routes/_layout/profile'
import { Route as LayoutPoliciesRouteImport } from './routes/_layout/policies'
import { Route as LayoutNodesRouteImport } from './routes/_layout/nodes'
import { Route as LayoutNetworksRouteImport } from './routes/_layout/networks'
import { Route as LayoutGroupsRouteImport } from './routes/_layout/groups'
import { Route as LayoutAuditRouteImport } from './routes/_layout/audit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsersRoute = LayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTasksRoute = LayoutTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSessionsRoute = LayoutSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileRoute = LayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPoliciesRoute = LayoutPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNodesRoute = LayoutNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNetworksRoute = LayoutNetworksRouteImport.update({
  id: '/networks',
  path: '/networks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGroupsRoute = LayoutGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuditRoute = LayoutAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof LayoutAuditRoute
  '/groups': typeof LayoutGroupsRoute
  '/networks': typeof LayoutNetworksRoute
  '/nodes': typeof LayoutNodesRoute
  '/policies': typeof LayoutPoliciesRoute
  '/profile': typeof LayoutProfileRoute
  '/sessions': typeof LayoutSessionsRoute
  '/tasks': typeof LayoutTasksRoute
  '/users': typeof LayoutUsersRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/audit': typeof LayoutAuditRoute
  '/groups': typeof LayoutGroupsRoute
  '/networks': typeof LayoutNetworksRoute
  '/nodes': typeof LayoutNodesRoute
  '/policies': typeof LayoutPoliciesRoute
  '/profile': typeof LayoutProfileRoute
  '/sessions': typeof LayoutSessionsRoute
  '/tasks': typeof LayoutTasksRoute
  '/users': typeof LayoutUsersRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/audit': typeof LayoutAuditRoute
  '/_layout/groups': typeof LayoutGroupsRoute
  '/_layout/networks': typeof LayoutNetworksRoute
  '/_layout/nodes': typeof LayoutNodesRoute
  '/_layout/policies': typeof LayoutPoliciesRoute
  '/_layout/profile': typeof LayoutProfileRoute
  '/_layout/sessions': typeof LayoutSessionsRoute
  '/_layout/tasks': typeof LayoutTasksRoute
  '/_layout/users': typeof LayoutUsersRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit'
    | '/groups'
    | '/networks'
    | '/nodes'
    | '/policies'
    | '/profile'
    | '/sessions'
    | '/tasks'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/audit'
    | '/groups'
    | '/networks'
    | '/nodes'
    | '/policies'
    | '/profile'
    | '/sessions'
    | '/tasks'
    | '/users'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/audit'
    | '/_layout/groups'
    | '/_layout/networks'
    | '/_layout/nodes'
    | '/_layout/policies'
    | '/_layout/profile'
    | '/_layout/sessions'
    | '/_layout/tasks'
    | '/_layout/users'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/users': {
      id: '/_layout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof LayoutUsersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tasks': {
      id: '/_layout/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof LayoutTasksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sessions': {
      id: '/_layout/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof LayoutSessionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile': {
      id: '/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/policies': {
      id: '/_layout/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof LayoutPoliciesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/nodes': {
      id: '/_layout/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof LayoutNodesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/networks': {
      id: '/_layout/networks'
      path: '/networks'
      fullPath: '/networks'
      preLoaderRoute: typeof LayoutNetworksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/groups': {
      id: '/_layout/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof LayoutGroupsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/audit': {
      id: '/_layout/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof LayoutAuditRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAuditRoute: typeof LayoutAuditRoute
  LayoutGroupsRoute: typeof LayoutGroupsRoute
  LayoutNetworksRoute: typeof LayoutNetworksRoute
  LayoutNodesRoute: typeof LayoutNodesRoute
  LayoutPoliciesRoute: typeof LayoutPoliciesRoute
  LayoutProfileRoute: typeof LayoutProfileRoute
  LayoutSessionsRoute: typeof LayoutSessionsRoute
  LayoutTasksRoute: typeof LayoutTasksRoute
  LayoutUsersRoute: typeof LayoutUsersRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuditRoute: LayoutAuditRoute,
  LayoutGroupsRoute: LayoutGroupsRoute,
  LayoutNetworksRoute: LayoutNetworksRoute,
  LayoutNodesRoute: LayoutNodesRoute,
  LayoutPoliciesRoute: LayoutPoliciesRoute,
  LayoutProfileRoute: LayoutProfileRoute,
  LayoutSessionsRoute: LayoutSessionsRoute,
  LayoutTasksRoute: LayoutTasksRoute,
  LayoutUsersRoute: LayoutUsersRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
